name: Deploy to VPS

on:
  push:
    branches:
      - master  # Adjust the branch as necessary

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      run: |
        docker build -t editor .
        docker save editor > editor.tar

    - name: Deploy to VPS with password
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install sshpass -y
        sshpass -p "$VPS_PASSWORD" scp editor.tar $VPS_USER@$VPS_HOST:/home/$VPS_USER/editor/
        sshpass -p "$VPS_PASSWORD" ssh $VPS_USER@$VPS_HOST "
          cd ~/editor &&
          docker load < editor.tar &&
          docker-compose down &&
          docker-compose up -d
        "
